[profile.default]
# Proje dizinleri
src = 'src'
out = 'out'
libs = ['lib']

# Derleyici ayarları (Remix ile aynı)
solc_version = '0.8.24'
evm_version = 'shanghai'

# Optimize ayarı (Remix'teki optimization 200)
optimizer = true
optimizer_runs = 200

# RPC endpointleri (Monad testnet bağlantısı)
[rpc_endpoints]
monad_testnet = "https://testnet-rpc.monad.xyz"

# Doğrulama (verify) için config
[etherscan]
monad_testnet = { key = "verify" }
